FROM php:7.4.23-fpm-alpine3.13

MAINTAINER php7.4.23 amqp weblfe dev

COPY queue.sh /bin/init.sh

ENV PHPIZE_DEPS \
		autoconf \
		dpkg-dev dpkg \
		file \
		g++ \
		gcc \
		libc-dev \
		make \
		pkgconf \
		re2c

RUN apk add --no-cache \
		ca-certificates \
		curl \
		tar \
		xz \
		imagemagick-dev  \
		imagemagick  \
		libmcrypt-dev  \
		libmcrypt  \
		libwebp-dev  \
		libwebp  \
		jpeg-dev  \
		jpeg  \
		libpng-dev \
		libpng \
		libxpm-dev \
		libxpm \
        freetype-dev \
        freetype \
        postgresql-dev \
        openldap-dev \
        libzip-dev \
        gmp-dev \
        protobuf-c-dev \
        protobuf-dev \
        php7-mbstring \
        && apk add --no-cache -U rabbitmq-c \
		&& apk add --no-cache -U rabbitmq-c-dev

RUN set -eux; \
	apk add --no-cache --virtual .build-deps \
		$PHPIZE_DEPS \
		argon2-dev \
		coreutils \
		curl-dev \
		libsodium-dev \
		libxml2-dev \
		openssl-dev \
		readline-dev \
		sqlite-dev \
		; \
    chmod 755 /bin/init.sh; \
    pecl install http://pecl.php.net/get/amqp-1.9.4.tgz; \
    docker-php-ext-enable amqp; \
    pecl install redis-5.3.4; \
    pecl install imagick-3.5.1; \
    pecl install mcrypt-1.0.3; \
    pecl install protobuf-3.17.3; \
    pecl install mongodb-1.10.0; \
    docker-php-ext-enable imagick \
            redis \
            mcrypt \
            protobuf \
            mongodb \
    ; \
    docker-php-ext-install gd \
         mysqli \
         opcache \
         pdo \
         pdo_mysql \
         pdo_pgsql \
         pgsql \
         ldap \
         intl \
         gmp \
         zip \
         bcmath \
         fileinfo \
         pcntl \
         sockets \
         iconv \
         exif \
    ; \
    apk del --no-network .build-deps

RUN set -eux; \
   { \
                echo 'opcache.memory_consumption=128'; \
                echo 'opcache.interned_strings_buffer=8'; \
                echo 'opcache.max_accelerated_files=4000'; \
                echo 'opcache.revalidate_freq=60'; \
                echo 'opcache.fast_shutdown=1'; \
                echo 'opcache.enable_cli=1'; \
   } > /usr/local/etc/php/conf.d/opcache-recommended.ini; \
   { \
                echo 'error_log=/var/log/php/php-error.log'; \
                echo 'display_errors=Off'; \
                echo 'log_errors=On'; \
                echo 'display_startup_errors=Off'; \
                echo 'date.timezone=UTC'; \
   } > /usr/local/etc/php/conf.d/php.ini; \
   cd /usr/local/etc; \
   { \
		echo '[www]'; \
		echo 'chdir = /home/site/wwwroot/'; \
		echo; \
		echo 'pm.max_children = 30'; \
   } | tee php-fpm.d/app.conf

RUN mkdir /var/log/php

ENV PHP_VERSION 7.4.23
ENV PORT 9000

WORKDIR /home/site/wwwroot/

ENTRYPOINT ["php-fpm"]
